### ISSUE TITLE
Repair process

### ISSUE THREAD

**Issue by Ahmeed2m** [ay-esm/SWE-2#4]
# Description :
This is test

# Conditions of Satisfaction :
-The user should report on the system when the part is being repaired.
-The user should report on the system when the part is repaired and waiting the customer to receive.

# Tasks:
  - [ ] Understanding the story. 
  - [x] Front End.
  - [ ] Back End.

**Comment by alielrafeiFCIH** [comment]
Add customer Add order front end 

1aa1756cbdff15ea6468eaae831878ef3d8e6a16
